TC-13: Add new endpoint to calculate tax amount for all the states.
sbandaru-cpal/coding-solutions pull request #22
Opened 2018-04-21 23:23 UTC by creddy-cpal

2018-04-22 00:05 UTC, sbandaru-cpal requested changes
Address the comments

2018-04-22 00:05 UTC, sbandaru-cpal commented on services/tax-calculator/tax-calculator-service/src/main/java/com/cpal/tax/calculator/service/StateService.java
> +    private BigDecimal calculateTaxableAmount(BigDecimal price, BigDecimal taxRate) {
Can you create a TaxUtil class common/common-utils module

2018-04-22 00:05 UTC, sbandaru-cpal commented on services/tax-calculator/tax-calculator-api/src/main/java/com/cpal/tax/calculator/api/TaxPrice.java
> +    private String stateCode;
this needs to be State enum

2018-04-22 00:05 UTC, sbandaru-cpal commented on services/tax-calculator/tax-calculator-service/src/main/java/com/cpal/tax/calculator/dao/StateDAO.java
> +    public BigDecimal findStateTaxRate(String state) {
keep it as State enum, need to restrict to only the states in the State enum

2018-04-22 00:05 UTC, sbandaru-cpal commented on services/tax-calculator/tax-calculator-service/src/main/java/com/cpal/tax/calculator/service/StateService.java
> +        List<TypeData> states = getAllStates();
loop through State.values()

2018-04-22 00:05 UTC, sbandaru-cpal commented on services/tax-calculator/tax-calculator-service/src/main/java/com/cpal/tax/calculator/controller/TaxController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "/calculateAllStates/{price}")
calculate/allStates/{price}

2018-04-22 11:48 UTC, creddy-cpal commented on services/tax-calculator/tax-calculator-api/src/main/java/com/cpal/tax/calculator/api/TaxPrice.java
> +    private String stateCode;
Fixed..

2018-04-22 11:48 UTC, creddy-cpal commented on services/tax-calculator/tax-calculator-service/src/main/java/com/cpal/tax/calculator/controller/TaxController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "/calculateAllStates/{price}")
Fixed

2018-04-22 11:48 UTC, creddy-cpal commented on services/tax-calculator/tax-calculator-service/src/main/java/com/cpal/tax/calculator/dao/StateDAO.java
> +    public BigDecimal findStateTaxRate(String state) {
Fixed..

2018-04-22 11:49 UTC, creddy-cpal commented on services/tax-calculator/tax-calculator-service/src/main/java/com/cpal/tax/calculator/service/StateService.java
> +        List<TypeData> states = getAllStates();
Fixed.

2018-04-22 11:52 UTC, creddy-cpal commented on services/tax-calculator/tax-calculator-service/src/main/java/com/cpal/tax/calculator/service/StateService.java
> +    private BigDecimal calculateTaxableAmount(BigDecimal price, BigDecimal taxRate) {
Fixed.

2018-04-24 03:14 UTC, sbandaru-cpal approved these changes

2018-04-24 23:43 UTC, merged